project:
  type: book

book:
  title: "Test book with {brms}"
  author: "Norah Jones"
  date: "9/4/2025"

  site-url: "https://andrewheiss.github.io/gha-brms/"

  repo-url: "https://github.com/andrewheiss/gha-brms"
  repo-actions: [source, issue]

  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - long-guy.qmd
    - references.qmd

bibliography: references.bib

execute: 
  freeze: auto

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt
